"""Add profit_usdc_equiv to PairProfit

Revision ID: 835966e5e1ed
Revises: 
Create Date: 2026-06-15 21:27:30.805952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '835966e5e1ed'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pair_profit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profit_usdc_equiv', sa.Float(), nullable=False, server_default='0.0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pair_profit', schema=None) as batch_op:
        batch_op.drop_column('profit_usdc_equiv')

    # ### end Alembic commands ###
