"""drop alert per pair

Revision ID: 91f82b060b37
Revises: 271b0a298d36
Create Date: 2026-07-05 13:01:02.259020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91f82b060b37'
down_revision = '271b0a298d36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trading_pair', schema=None) as batch_op:
        batch_op.add_column(sa.Column('drop_alert_enabled', sa.Boolean(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('drop_alert_pct', sa.Float(), server_default='55.0', nullable=False))
        batch_op.add_column(sa.Column('drop_alert_auto', sa.Boolean(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trading_pair', schema=None) as batch_op:
        batch_op.drop_column('drop_alert_auto')
        batch_op.drop_column('drop_alert_pct')
        batch_op.drop_column('drop_alert_enabled')

    # ### end Alembic commands ###
